name: Fedora-PR-tests@TF

on:
  issue_comment:
    types:
      - created
jobs:
  build:
    # This job only runs for '[test]' pull request comments by owner, member
    name: Schedule test on Testing Farm service for Fedora
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request
      && contains(github.event.comment.body, '/test')
      && contains(fromJson('["OWNER","MEMBER"]'), github.event.comment.author_association)

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: "refs/pull/${{ github.event.issue.number }}/head"

      # https://github.com/sclorg/testing-farm-as-github-action
      - name: Schedule tests on external Testing Farm by Testing-Farm-as-github-action
        id: github_action
        uses: sclorg/testing-farm-as-github-action@main
        with:
          api_key: ${{ secrets.TF_PUBLIC_API_KEY }}
          git_url: "https://github.com/sclorg/sclorg-testing-farm"
          git_ref: "main"
          tf_scope: "public"
          tmt_plan_regex: "cwt"
          pull_request_status_name: "Fedora"
          variables: "REPO_URL=${{ github.server_url }}/${{ github.repository }};REPO_NAME=${{ github.repository }};PR_NUMBER=${{ github.event.issue.number }}"
          compose: "Fedora-latest"
          create_issue_comment: "true"
          create_github_summary: "true"
